- hosts: staging
  tasks:
    - name: Install required build packages
      apt:
        name: ["git"]

    - name: Add the user "benchmark" with a bash shell
      user:
        name: benchmark
        shell: /bin/bash

    - name: Git checkout repository
      git:
        repo: "https://github.com/ephes/web_benchmark"
        dest: /home/benchmark/site
      become: true
      become_user: benchmark

    - name: Install poetry
      shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | /usr/local/bin/python3.8
      args:
        warn: no
      become: true
      become_user: benchmark

    - name: Replace python3 in poetry bin with python3.8 :(
      lineinfile:
        path: /home/benchmark/.poetry/bin/poetry
        regexp: "python3"
        line: "#!/usr/bin/env python3.8"

    - name: Install poetry dependencies
      shell: /home/benchmark/.poetry/bin/poetry install
      args:
        chdir: /home/benchmark/site
      become: true
      become_user: benchmark

    # Gunicorn
    - name: Create a symbolic link for gunicorn systemd service
      file:
        src: /home/benchmark/site/web_benchmark.service
        dest: /etc/systemd/system/web_benchmark.service
        state: link

    - name: Make sure web_benchmark gunicorn service is running
      systemd:
        state: restarted
        name: web_benchmark

    - name: Create a symbolic link for traefik loadbalancer
      file:
        src: /home/benchmark/site/web_benchmark.traefik.yml
        dest: /etc/traefik/dynamic/web_benchmark.traefik.yml
        state: link

    # Uvicorn
    - name: Create a symbolic link for uvicorn systemd service
      file:
        src: /home/benchmark/site/web_benchmark_async.service
        dest: /etc/systemd/system/web_benchmark_async.service
        state: link

    - name: Make sure web_benchmark uvicorn  service is running
      systemd:
        state: restarted
        name: web_benchmark
